apiVersion: apps/v1
kind: Deployment
metadata:
  name: troia-front-webapp-deployment
  labels:
    app: troia-front-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troia-front-webapp
  template:
    metadata:
      labels:
        app: troia-front-webapp
    spec:
      containers:
      - name: troia-front-webapp
        image: docker.io/janezmk/troia-front-webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: db-config