apiVersion: v1
kind: Service
metadata:
  name: troia-front-webapp-service
spec:
  selector:
    app: troia-front-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer